<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <PackageId>Magomedali.FileService.Contracts</PackageId>
      <Version>0.0.1-preview.1</Version>
      <IsPackable>true</IsPackable>
      <Authors>MagomedaliTech</Authors>
      <Company>MagomedaliTech</Company>
      <RepositoryUrl>https://github.com/MagomedaliGajiev/magomedali-tech</RepositoryUrl>
      <RepositoryType>git</RepositoryType>
      <PackageDescription>
        Contracts and HTTP communication client for Magomedali FileService
      </PackageDescription>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" />
      <PackageReference Include="Magomedali.Shared.SharedKernel" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="FileService.IntegrationTests" />
    </ItemGroup>

</Project>
