// <auto-generated />
using System;
using FileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    partial class FileServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("media_assets", (string)null);

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.Assets.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("PREVIEW");
                });

            modelBuilder.Entity("FileService.Domain.Assets.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("VIDEO");
                });

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ExpectedChunksCount")
                                .HasColumnType("integer")
                                .HasColumnName("expected_chunks_count");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("media_type");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("content_type");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("file_extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("character varying(512)")
                                        .HasColumnName("file_name");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.OwnsOne("FileService.Domain.MediaOwner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("owner_context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_entity_id");

                            b1.HasKey("MediaAssetId");

                            b1.HasIndex("Context", "EntityId")
                                .HasDatabaseName("ix_media_assets_owner");

                            b1.ToTable("media_assets");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.StorageKey", "Key", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("storage_key");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("storage_location");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("storage_prefix");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("Key")
                        .IsRequired();

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}