<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <PackageId>Magomedali.Shared.Core</PackageId>
    </PropertyGroup>
  
    <ItemGroup>
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared.SharedKernel\Shared.SharedKernel.csproj" />
    </ItemGroup>

</Project>
